INSERT INTO tb_estado VALUES ( 11, 'Rondônia', 'RO');
INSERT INTO tb_estado VALUES ( 12, 'Acre', 'AC');
INSERT INTO tb_estado VALUES ( 13, 'Amazonas', 'AM');
INSERT INTO tb_estado VALUES ( 14, 'Roraima', 'RR');
INSERT INTO tb_estado VALUES ( 15, 'Pará', 'PA');
INSERT INTO tb_estado VALUES ( 16, 'Amapá', 'AP');
INSERT INTO tb_estado VALUES ( 17, 'Tocantins', 'TO');
INSERT INTO tb_estado VALUES ( 21, 'Maranhão', 'MA');
INSERT INTO tb_estado VALUES ( 22, 'Piauí', 'PI');
INSERT INTO tb_estado VALUES ( 23, 'Ceará', 'CE');
INSERT INTO tb_estado VALUES ( 24, 'Rio Grande do Norte', 'RN');
INSERT INTO tb_estado VALUES ( 25, 'Paraíba', 'PB');
INSERT INTO tb_estado VALUES ( 26, 'Pernambuco', 'PE');
INSERT INTO tb_estado VALUES ( 27, 'Alagoas', 'AL');
INSERT INTO tb_estado VALUES ( 28, 'Sergipe', 'SE');
INSERT INTO tb_estado VALUES ( 29, 'Bahia', 'BA');
INSERT INTO tb_estado VALUES ( 31, 'Minas Gerais', 'MG');
INSERT INTO tb_estado VALUES ( 32, 'Espírito Santo', 'ES');
INSERT INTO tb_estado VALUES ( 33, 'Rio de Janeiro', 'RJ');
INSERT INTO tb_estado VALUES ( 35, 'São Paulo', 'SP');
INSERT INTO tb_estado VALUES ( 41, 'Paraná', 'PR');
INSERT INTO tb_estado VALUES ( 42, 'Santa Catarina', 'SC');
INSERT INTO tb_estado VALUES ( 43, 'Rio Grande do Sul', 'RS');
INSERT INTO tb_estado VALUES ( 50, 'Mato Grosso do Sul', 'MS');
INSERT INTO tb_estado VALUES ( 51, 'Mato Grosso', 'MT');
INSERT INTO tb_estado VALUES ( 52, 'Goiás', 'GO');
INSERT INTO tb_estado VALUES ( 53, 'Distrito Federal', 'DF');
